// STUB: implemented in vertical E (recurring bills).
// Owner: Vertical E. Do not edit this file from another vertical.
//
// Expected behaviour: every `RecurringBill` template with its vendor, cadence,
// amount, next run date, paused state and when it last generated — plus a
// "Generate now" action on the ones that are due. Generating creates DRAFT
// bills with `recurringBillId` set and the template's line items copied in, so
// the draft arrives already coded, then advances `nextRunDate` and stamps
// `lastGeneratedAt`.
//
// Reuse, do not re-implement the schedule maths (`src/lib/recurring.ts`):
// `dueOccurrences(template, today)` says how many bills are owed — a template
// can owe more than one, and generating only the newest silently loses the
// rest — and `nextRunDateAfter(template, today)` gives the date to store, so
// "generate now" can neither duplicate an occurrence nor skip one.
// `upcomingOccurrences(template, 3)` drives the "next runs" preview.
//
// The seed ships four templates: two already due (WeWork rent, Northgate
// insurance), one upcoming (Figma) and one paused (Sparkle City).
//
// Vertical E also owns the create/edit routes under `src/app/(app)/recurring/`.
// Reads its own data server-side; this component takes no props.

import { StubPanel } from "@/components/common/stub-panel";

export function RecurringList() {
  return (
    <StubPanel
      title="Recurring bills"
      owner="Vertical E — recurring bills"
      summary="Templates that generate coded drafts on a schedule, with their next run date and a generate-now action."
    />
  );
}
