// STUB: implemented in vertical D (ingestion — OCR upload/review + CSV import).
// Owner: Vertical D. Do not edit this file from another vertical.
//
// Expected behaviour: a CSV import wizard in three steps — upload a file, map
// its columns onto bill fields (vendor, bill number, issue date, terms, total,
// and optionally line description / quantity / unit price / GL code /
// department), then preview every parsed row with its validation state before
// committing. Rows that resolve cleanly are created as DRAFT bills with
// `source = CSV`; rows that do not are reported per-row with a reason and are
// never partially written. A downloadable sample CSV removes the guesswork.
//
// Reuse, do not re-implement: `parseAmountToCents` for money (never parseFloat),
// `fromDateInputValue` for dates, `dueDateFrom(issueDate, terms)` for the due
// date, and `@@unique([vendorId, billNumber])` for duplicate detection —
// surface a collision as a row-level error rather than throwing.
//
// Reads its own data (vendors, GL accounts, current user) server-side, so the
// page that renders it stays a plain shell and never has to change shape.

import { StubPanel } from "@/components/common/stub-panel";

export function ImportWizard() {
  return (
    <StubPanel
      title="CSV import"
      owner="Vertical D — ingestion"
      summary="Upload a CSV, map its columns onto bill fields, preview every row with its validation state, then create the drafts."
    />
  );
}
