// STUB: implemented in vertical D (ingestion — OCR upload/review + CSV import).
// Owner: Vertical D. Do not edit this file from another vertical.
//
// Expected behaviour: upload an invoice DOCUMENT (PDF/image), run extraction
// against it, and create a DRAFT bill with `source = OCR` from the structured
// result — never a finished bill (ADR 0010). Each run is persisted as an
// `OcrExtraction` row (rawResult, provider, confidenceBasisPoints) so the
// extraction is auditable and re-reviewable rather than silently overwriting
// what a person typed, and re-running appends rather than replaces.
//
// Because extracted lines usually do not reconcile to the extracted total, the
// draft is expected to land in the derived `Missing info` state — that is the
// feature working, not failing. Do not "fix" the total from the lines: the bill
// total is authoritative (ADR 0004).
//
// Confidence is stored in BASIS POINTS (0–10000); render it with the same
// convention `formatBasisPoints` uses rather than inventing a second one.
//
// Reads its own data server-side; the page that renders it takes no props.

import { StubPanel } from "@/components/common/stub-panel";

export function InvoiceUpload() {
  return (
    <StubPanel
      title="Invoice upload and OCR"
      owner="Vertical D — ingestion"
      summary="Upload an invoice document, extract it into a structured draft, and keep the raw run for review."
    />
  );
}
