// STUB: implemented in vertical D (ingestion — OCR upload/review + CSV import).
// Owner: Vertical D. Do not edit this file from another vertical.
//
// Expected behaviour: the review half of OCR, rendered on the bill detail page
// beside the document it came from. Shows the most recent `OcrExtraction` for
// the bill — provider, when it ran, overall confidence — field by field, with
// what the extractor read NEXT TO what the bill currently says, so a
// disagreement is visible instead of implicit. Low-confidence fields are
// flagged, the extractor's own warnings are listed, and each field can be
// accepted onto the bill individually. Accepting is a normal edit: it goes
// through vertical B's editing rules and appends an `Activity`.
//
// The seed ships one run attached to IPS-3391, whose scanned total ($6,890)
// disagrees with its extracted lines ($6,240) — the demo case for this panel.
//
// It renders NOTHING when the bill has no extraction, which is most bills, so
// the detail page can mount it unconditionally.

import { StubPanel } from "@/components/common/stub-panel";
import type { BillDetail } from "@/server/bill-detail";

export interface OcrReviewPanelProps {
  bill: BillDetail;
}

export function OcrReviewPanel({ bill }: OcrReviewPanelProps) {
  const extraction = bill.ocrExtractions[0];
  if (!extraction) return null;

  return (
    <StubPanel
      title="OCR review"
      owner="Vertical D — ingestion"
      summary={`Extracted by ${extraction.provider}: compare each read field against the bill and accept it, or leave it alone.`}
    />
  );
}
